# Generated by Django 5.0.7 on 2024-07-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_question_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='images',
            field=models.ManyToManyField(blank=True, to='questions.image'),
        ),
        migrations.AddField(
            model_name='question',
            name='images',
            field=models.ManyToManyField(blank=True, to='questions.image'),
        ),
    ]
