# Generated by Django 5.0.7 on 2024-07-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_alter_question_created_at_alter_question_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='images',
        ),
        migrations.RemoveField(
            model_name='question',
            name='images',
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
